Add support for custom G.A.M.M.A repository
Mord3rca/gamma-launcher pull request #136
Opened 2024-07-15 18:39 UTC by sobkas

Ability to use custom G.A.M.M.A repository from Github
I don't think there are other sites with forks so for now only Github support

2024-07-16 19:57 UTC, sobkas commented
Any ideas?

2024-07-16 20:11 UTC, Mord3rca requested changes

2024-07-16 20:11 UTC, Mord3rca commented on launcher/commands/install.py
> +            "default": None,
`"default": "Grokitach/Stalker_GAMMA",`

2024-07-16 20:11 UTC, Mord3rca commented on launcher/commands/install.py
> +        self._repo = 'Grokitach/Stalker_GAMMA'
`self._repo = None`

2024-07-16 20:11 UTC, Mord3rca commented on launcher/commands/install.py
> +            self._repo = args.custom_repo
Always set repo from args since now, default value is correct

2024-07-16 20:13 UTC, Mord3rca commented
Sorry, a bit busy at the moment.

Only Github support for now is fine. Minor changes to do and I'll find a moment to test this

2024-09-29 09:55 UTC, Mord3rca commented
Merged in #150

2024-09-29 09:55 UTC, closed without merging