Easy python venv install instructions
Mord3rca/gamma-launcher pull request #17
Opened 2023-05-08 21:57 UTC by zarong-465465

I think my last attempt at this got messed up, but here is a quick and easy venv install guide for this.

Not 100% sure about the Windows commands, I just stole those from python's website.

2023-05-11 17:48 UTC, Mord3rca requested changes

2023-05-11 17:48 UTC, Mord3rca commented on README.md
> +It's strongly advised to install this in a [venv](https://docs.python.org/3/library/venv.html#creating-virtual-environments) (Python Virtual Environment)
Please change the venv link to this guide: https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment

2023-05-12 16:44 UTC, zarong-465465 commented on README.md
> +It's strongly advised to install this in a [venv](https://docs.python.org/3/library/venv.html#creating-virtual-environments) (Python Virtual Environment)
There you go

2023-05-12 16:44 UTC, zarong-465465 commented
Updated link

2023-05-14 16:22 UTC, Mord3rca approved these changes

2023-05-14 16:22 UTC, merged